[package]
name = "iteratail"
version = "0.1.0-alpha.1"
edition = "2024"
license = "MIT"
description = "Iterator that can yield a value after iteration over."
readme = "README.md"
repository = "https://github.com/NewYearPrism/rust-iteratail.git"

[dependencies]
